# **Quality check segmentations**

***Prior to this notebook, you should have already completed the organelle and masks segmentations using notebooks 1.0 through 1.8 and/or batch_processing_segmentations OR completed segmentations using the `infer-subc` plugin for Napari.***

### **Purpose**
The purpose of this notebook is to:
1. Visually inspect the segmentation outputs for each image in your dataset (***optional***)

    We highly recommend going through this process. It is especially important for datasets where errors in the segmentations can have large impacts on the downstream statistical outcomes (e.g., datasets that do NOT have ~100+ images per condition for example).
2. Separation of the `masks` file into separate `cell` and `nuc` segmentation files (***required***)

    This is required for downstream analysis in `infer-subc` Part 2. For some background, this step is required due to technical limitations of the Napari plugin; each workflow can only output one file, but the segmentations of the nucleus and cell are derived from the same workflows.

### ➡️ **Input**
The following files will be used as input in this notebook:
1. "Raw" confocal microscopy image (".tiff", ".tif", or ".czi") where each channel of the image represents one of the organelles being segmented
2. The segmentation files created in `infer-subc` Notebooks or Napari plugin or derived from alternative segmentation tools.

You will also need the following:
1. An empty folder to save segmentation files after editing
2. An empty folder to save the FINAL segmentation dataset (e.g., combining edited files with original segmentation files that did not need editing)

### **Output** ➡️
The output from this notebook will include:
1. A new folder containing any edited mask files saved as ".tiff"
2. A new folder containing ALL FINAL segmentation files that are ready for quantification

-----

### 👣 **Summary of steps**  

➡️ **QUALITY CHECK SEGMENTATIONS**
- **`Step 1`** - Define the paths to your data and final output location

- **`Step 2`** - Import and visualize organelle and region segmentations

- **`Step 3`** - Edit individual segmentations (***optional***) 

- **`Step 4`** - Computer check segmentations before quantification

- **`Step 5`** - Save organelle and region segmentations into specified folder

    - This step will also save the cell and nuclei segmentations as separate files (***required***)

---------------------
## **IMPORTS**

#### &#x1F3C3; **Run code; no user input required**

In [1]:
import os
from pathlib import Path
import pandas as pd
import numpy as np
from typing import Union

import napari
from napari.utils.colormaps import Colormap
from napari.settings import get_settings
settings = get_settings()
settings.application.ipy_interactive = True

viewer = napari.Viewer()

import colorsys
from infer_subc.core.file_io import (read_czi_image,
                                        export_inferred_organelle,
                                        import_inferred_organelle,
                                        list_image_files,)
from infer_subc.utils.batch import filter_segmentation, edit_segmentation, QC_filter, label

%load_ext autoreload
%autoreload 2

C:\Users\zscoman\AppData\Local\Temp\ipykernel_23276\1288589443.py:3: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

-----

## **QUALITY CHECK OF SEGMENTATIONS**

**NOTE: DO NOT EDIT ANY OF THE LAYER NAMES IN NAPARI**

### **`STEP 1` - Define the paths to your data**

#### &#x1F6D1; &#x270D; **User Input Required:**

If you are not using sample data, please specify the following information about your data: 
- `raw_path`: A string of the path to your raw (e.g., intensity) images that were used as the input for segmentation
- `seg_path`: A string of the path where the segmentation outputs will be saved
- `location_tosave_fullset_gooddata`: A string to an empty folder that will contain all of the FINAL segmentation files (e.g., it will combine the newly saved edited segmentation files with any of the original segmentation files that did not need editing)
- `raw_file_type`: The raw file type (e.g., ".tiff" or ".czi")
- `seg_file_type`: The segmentation file type (e.g., ".tiff" or ".tif" if you were using infer-subc notebooks or Napari plugin)
- `suffixes`: A list of the endings of your segmentation file names; this usually just includes the segmentation suffix (e.g., 'lyso'), but may also include additional text if the settings file in Napari or the 'name_suffix' in the batch_process_segmentation notebook contained additional text. 
- `channels`: A list of indexes of the channels in the raw intensity image used to generate the segmentation corresponding to the same locations in the list of their suffixes. Channel indexes begin at 0 for channel 1. For objects that have no specific channels, please input a value of None
- `multichannel`: A dictionary with some values in suffixes assigned to a list of names to split the multichannel segmentation into. For example, {'mask': ['nuc', 'cell']} due to the 'mask' file containing both the cell mask and nucleus segmentations.

Otherwise, input the type of sample data:
- `None`: No sample data
- `'neuron_1'`: Using the neuron_1 sample data
- `'astrocyte'`: Using the astrocyte sample data
- `'neuron_2'`: Using the neuron_2 sample data
- `'iPSC'`: Using the iPSC sample data

In [2]:
### USER INPUT REQUIRED ###
sample_data_type = None # Options: None, 'neuron_1', 'astrocyte', 'neuron_2', 'iPSC'

In [3]:
#### USER INPUT REQUIRED ###
raw_data = "D:/APOE Mutant Images/Deconvolved"
seg_path = "D:/APOE Mutant Images/Segmented"

location_tosave_fullset_gooddata = "D:/APOE Mutant Images/goodsegs"

raw_file_type = ".tiff"
seg_file_type = ".tiff"

suffixes = ['mask', 'lyso2 workflow', 'mito', 'APOE371_BR1_N07', 'peroxisome workflow', 'ER', 'Lipid Droplet Workflow']
channels = [None, 2,3,4,5,6,0]
multichannel = {'mask': ['nuc', 'cell'], 
                'soma_neurites': ['soma', 'neurites']}

#### &#x1F6D1; &#x270D; ***Optional* User Input Required:**

&#x1F453; **FYI:** If you ran the batch processing more than once, you can include information about the additional segmentation location and file suffixes here. If you do **NOT** have a second file location, for each object below, please indicate: `None`

***Important:** Only one location for each segmentation type will be used. If `lyso` and `lyso__2` are both specified at the same location in the list, **ONLY** `lyso_2` will be visualized in the below steps.*

In [4]:
#### Optional - USER INPUT REQUIRED ###
seg_path_2 = "D:/APOE Mutant Images/Segmented Mask v2"

suffixes_2 = ["cell", None, None, None, None, None, "ld v2"]

#### &#x1F3C3; **Run code; no user input required**
&#x1F453; **FYI:** If sample data is chosen, this code block will set up all the paths and variable for you; otherwise, this code block will do nothing.

In [5]:
if sample_data_type != None:
    sd_fol = Path(os.getcwd()).parents[1] / "sample_data"

    raw_data =  sd_fol / f"example_{sample_data_type}"/ "raw"
    seg_path = sd_fol / f"example_{sample_data_type}"/ "raw"

    location_tosave_edited_segmentations = sd_fol / "example_quant" / "edit_seg"
    location_tosave_fullset_gooddata = sd_fol / "example_quant" / "seg"

    raw_file_type = ".tiff"
    seg_file_type = ".tiff"
    if sample_data_type == "neuron_1":
        suffixes = ['masks_A', 'lyso', 'mito', 'golgi', 'perox', 'ER', 'LD']
        channels = [3, 4, 2, 5, 1, 0]
        multichannel = {'masks_A': ['nuc', 'cell']}
    if sample_data_type == "astrocyte":
        suffixes = ['masks_B', 'lyso', 'mito', 'golgi', 'perox', 'ER', 'LD']
        channels = [3, 4, 2, 5, 1, 0]
        multichannel = {'masks_B': ['nuc', 'cell']}
    if sample_data_type == "neuron_2":
        suffixes = ['masks_C', 'lyso', 'mito', 'golgi', 'perox', 'ER', 'LD']
        channels = [4, 3, 2, 1, 0, 6]
        multichannel = {'masks_C': ['nuc', 'cell']}
    if sample_data_type == "iPSC":
        suffixes = ['masks_D', 'lyso', 'mito', 'golgi', 'perox', 'ER', 'LD']
        channels = [2, 3, 4, 5, 6, 0]
        multichannel = {'masks_D': ['nuc', 'cell']}

#### &#x1F3C3; **Run code; no user input required**
&#x1F453; **FYI:** This code block will print the list of raw file names in your raw_path. You will want to review each file in the list for accurate segmentations. The next set of code blocks will walk you how to do this.

In [6]:
raw_file_list = list_image_files(Path(raw_data),".tiff")

pd.set_option('display.max_colwidth', None)
pd.DataFrame({"Image Name":raw_file_list})

                                                                                                            Image Name
0    D:\APOE Mutant Images\Deconvolved\07112023_ZS_MSi08-L_iPSCsundiff_APOE371_BR1_N01_Linear_unmixing_0_cmle.ome.tiff
1    D:\APOE Mutant Images\Deconvolved\07112023_ZS_MSi08-L_iPSCsundiff_APOE371_BR1_N02_Linear_unmixing_0_cmle.ome.tiff
2    D:\APOE Mutant Images\Deconvolved\07112023_ZS_MSi08-L_iPSCsundiff_APOE371_BR1_N03_Linear_unmixing_0_cmle.ome.tiff
3    D:\APOE Mutant Images\Deconvolved\07112023_ZS_MSi08-L_iPSCsundiff_APOE371_BR1_N04_Linear_unmixing_0_cmle.ome.tiff
4    D:\APOE Mutant Images\Deconvolved\07112023_ZS_MSi08-L_iPSCsundiff_APOE371_BR1_N05_Linear_unmixing_0_cmle.ome.tiff
..                                                                                                                 ...
182              D:\APOE Mutant Images\Deconvolved\08042023_ZS_MSi08L_APOE_870_BR3_N08_Linear_unmixing_0_cmle.ome.tiff
183              D:\APOE Mutant Images\Deconvolved\08042023_ZS_MSi08L_APOE_870_BR3_N09_Linear_unmixing_0_cmle.ome.tiff
184              D:\APOE Mutant Images\Deconvolved\08042023_ZS_MSi08L_APOE_870_BR3_N10_Linear_unmixing_0_cmle.ome.tiff
185               D:\APOE Mutant Images\Deconvolved\08042023_ZS_MSi08L_APOE_WT_BR3_N01_Linear_unmixing_0_cmle.ome.tiff
186               D:\APOE Mutant Images\Deconvolved\08042023_ZS_MSi08L_APOE_WT_BR3_N02_Linear_unmixing_0_cmle.ome.tiff

[187 rows x 1 columns]

### **`STEP 2` - Import and visualize organelle and region segmentations**

#### &#x1F6D1; &#x270D; **User Input Required:**
&#x1F53C; Use the list  above to determine the index of the image you would like to look at. Eventually, you should look at all images. The pipeline below will indicate when you need to return here to repeat for the next image in the list.

In [7]:
#### USER INPUT REQUIRED ###
num = 7

#### &#x1F3C3; **Run code; no user input required**
&#x1F453; **FYI:** This code block will import the segmentation files associated to the raw image you selected above. The raw image and segmentations will be included in a Napari viewer for visual inspection.

In [ ]:
raw_img_data, raw_meta_dict = read_czi_image(raw_file_list[num])
viewer.add_image(raw_img_data, name='raw', blending='additive')
print("Image name:")
print(raw_meta_dict['name'][0].split(" :: ")[0])
obj_segs = {}

# Importing segmentations
for suffix, channel in zip(suffixes, channels):
    obj = import_inferred_organelle(suffix, raw_meta_dict, Path(seg_path), seg_file_type)
    if suffix not in multichannel.keys():
        if len(obj.shape) > 3:
            print(f"{suffix} is multichannel, splitting into unnamed separate channels")
            for i in range(int(obj.shape[0])-1):
                obj_segs[f"{suffix}_{i}"] = (obj[i], channel)
        else:
            obj_segs[suffix] = (obj, channel)
    else:
        if len(obj.shape) <= 3:
            print(f"{suffix} is not multichannel, ignoring")
            obj_segs[suffix] = (obj, channel)
        else:
            for i in range(int(obj.shape[0])-1):
                obj_segs[multichannel[suffix][i]] = (obj[i], channel)

for suffix2, suffix, channel in zip(suffixes_2, suffixes, channels):
    if suffix2 is not None:
        obj = import_inferred_organelle(suffix2, raw_meta_dict, Path(seg_path_2), seg_file_type)
        if suffix not in multichannel.keys():
            if len(obj.shape) > 3:
                print(f"{suffix2} is multichannel, splitting into unnamed separate channels")
                for i in range(int(obj.shape[0])-1):
                    obj_segs[f"{suffix}_{i}"] = (obj[i], channel)
            else:
                obj_segs[suffix] = (obj, channel)
        else:
            if len(obj.shape) <= 3:
                print(f"{suffix2} is not multichannel, ignoring")
                obj_segs[suffix] = (obj, channel)
            else:
                for i in range(int(obj.shape[0])-1):
                    obj_segs[multichannel[suffix][i]] = (obj[i], channel)

# Creating colorways
HSV_tuples = [(i/(len(obj_segs.keys())), 1, 1) for i in range(len(obj_segs.keys()))]
RGB_tuples = map(lambda x: colorsys.hsv_to_rgb(*x), HSV_tuples)
col = ["".join("%02X" % round(c*255) for c in rgb) for rgb in RGB_tuples]

for count, suffix in enumerate(obj_segs.keys()):
    cmap = Colormap(["#000000", f"#{col[count]}"], 
                    name=f'{suffix}_cmap')
    channel = obj_segs[suffix][1]
    obj = obj_segs[suffix][0]
    
    if channel is not None:
        viewer.add_image(raw_img_data[channel], name=f'{suffix}_raw', blending='additive')
    viewer.add_image(obj, opacity=0.3, name=f'{suffix}_seg', colormap=cmap)
obj_segs_edit = {key: None for key in obj_segs.keys()}

Image name:
07112023_ZS_MSi08-L_iPSCsundiff_APOE371_BR1_N08_Linear_unmixing_0_cmle.ome
loaded  inferred 4D `mask`  from D:\APOE Mutant Images\Segmented
loaded  inferred 3D `lyso2 workflow`  from D:\APOE Mutant Images\Segmented
loaded  inferred 3D `mito`  from D:\APOE Mutant Images\Segmented
loaded  inferred 3D `APOE371_BR1_N07`  from D:\APOE Mutant Images\Segmented
loaded  inferred 3D `peroxisome workflow`  from D:\APOE Mutant Images\Segmented
loaded  inferred 3D `ER`  from D:\APOE Mutant Images\Segmented
loaded  inferred 3D `Lipid Droplet Workflow`  from D:\APOE Mutant Images\Segmented
loaded  inferred 3D `cell`  from D:\APOE Mutant Images\Segmented Mask v2
cell is not multichannel, ignoring
loaded  inferred 3D `ld v2`  from D:\APOE Mutant Images\Segmented Mask v2

> #### &#x1F6D1; **STOP: Use the `Napari` window to review all of the segmentations for this image.** &#x1F50E;
>
> **At this point, take note of which segmentations need to be edited, if any. Once you are finished reviewing the segmentations for this image, continue on to the next sections to:**
> 1) Edit the segmentation (if necessary), then
> 2) Quality check the segmentation (if single object), then
> 2) Save the final set of segmentations for this image in a new folder. This step will also save the multichannel files (such as your mask file) as separate files (such as `cell` and `nuc` for the cell mask) in the final analysis location.

### **`STEP 3` - Edit segmentations *(optional)***

This step may be skipped if you are already satisfied with all of your segmentations. If so, please set the values in the user input section of this step all to `False`.

#### &#x1F3C3; **Run code; no user input required**
&#x1F453; **FYI:** The below block of code lists out the segmentations that you have viewed.

In [9]:
print(obj_segs.keys())

dict_keys(['nuc', 'cell', 'lyso2 workflow', 'mito', 'APOE371_BR1_N07', 'peroxisome workflow', 'ER', 'Lipid Droplet Workflow'])

#### &#x1F6D1; &#x270D; **User Input Required:**
Now that you visually inspected your image and the segmentation output files, indicate below which of the segmentations you would like to edit, if any, by typing one of the following options for each segmentation type corresponding to the segmentations listed by the above block of code:
- `True`: for any images you want to edit
- `False`: for any that you do not want to edit

In [10]:
obj_edit = [False, True, False, False, False, False, False, False]

#### &#x1F3C3; **Run code; no user input required**

For any image that you have decided to edit, the Napari viewer will be opened one at a time. When you are finished editing the image, close the Napari viewer (do not minimize it), and the code will proceed to the next image. This will repeat until you have cycled through all of your images. If you ever wish to restart editing any of the segmentations from the beginning, you can rerun this block of code after setting the images you do not wish to edit again as false in the obj_edit variable above and rerunning that block of code.

In [11]:
if len(obj_edit) != len(obj_segs.keys()):
    print("The number of values in the obj_edit variable is not equal to the number of object segmentations.")
    print("Please adjust the values in the obj_edit variable above, then rerun this block of code.")
for edit, suffix in zip(obj_edit, obj_segs.keys()):
    if (obj_segs_edit[suffix] is None) or edit:
        obj_segs_edit[suffix] = edit_segmentation(suffix, viewer, edit)
print("If you would like to restart editing any of the segmentations, you can change the obj_edit variable to only select for objects desired to be edited and rerun this block of code.")

You have chosen to edit the segmentation for cell
No raw image found for cell, adding the 'raw' layer instead.
If you would like to restart editing any of the segmentations, you can change the obj_edit variable to only select for objects desired to be edited and rerun this block of code.

> #### &#x1F6D1; **STOP: Use the `Napari` window to edit chosen segmentations.** &#x1F50E;
>
> **At this point, a `Napari` window will have opened one of the chosen segmentations to edit. Within this Napari window, do NOT change the names of any of the layers. Once you have finished editing the image, do the following:**
> 1) You may manually save the segmentation to another location; however, this occurs automatically later. (optional)
> 2) Close out of all `Napari` windows (do not minimize).
>
> A new `Napari` window will open up so long as there are more segmentations you have chosen to edit.

### **`STEP 4` - Automatically check segmentations**

These automatic quality checks run on your segmentations will ensure that any images that are designed to be single-objects (such as cell masks) are single objects. This ensures that any editing you may have made will not result in extraneous objects that were unintended to be generated.

#### &#x1F3C3; **Run code; no user input required**
&#x1F453; **FYI:** The below block of code lists out the segmentations that you have viewed.

In [12]:
print(obj_segs.keys())

dict_keys(['nuc', 'cell', 'lyso2 workflow', 'mito', 'APOE371_BR1_N07', 'peroxisome workflow', 'ER', 'Lipid Droplet Workflow'])

#### &#x1F6D1; &#x270D; **User Input Required:**

Now that you have edited your files, indicate below which quality check filter you would like to apply for each segmentation type corresponding to the listed segmentation types above:

- `None`: For any images that you don't want to run the quality check filter on or must contain multiple objects
- `'brightest'`: To ensure that the only remaining object in the image is the brightest object (only 1 object remains)
- `'largest'`: To ensure that only the largest object remains after the quality check filter (only 1 object remains)
- `int`: Any integer value of voxels the remaining object must be larger than (only 1 object remains)

NOTE: Setting an int value of 0 simply runs the quality checks without making any changes to try to make the image conform to the assumptions. Use this if you do not wish for the computer to make any automatic adjustments to your image.

In [13]:
quality_filter = [None, 100, None, None, None, None, None, None]

#### &#x1F3C3; **Run code; no user input required**

Be sure to follow the instructions provided at the end of the below block of code to determine if you need to return to an earlier block of code or you may proceed. In some instances, you may be allowed to edit your segmentation here without needing to rerun the editing process; in these cases, be sure that you only edit the object_seg layer and not the object_seg_filtered layer. 

The object_seg layer is the segmentation prior to the computer attempting to run a filter to correct any problems with the image. The object_seg_filtered layer is the segmentation after the computer attempted to run a filter to correct any problems with the image. Editing the object_seg_filtered layer will result in the computer rerunning the quality check filter on the unfiltered image, resulting in a loss of work.

In [14]:
# def filter_segmentation(suffix, filt, edited, raw, status):
#     if not (filt is None):
#         if len(np.unique(label(edited))) > 2:
            
#             status = "Fail"
#             viewer2 = napari.Viewer()
#             print(f"Your {suffix} segmentation contains MORE THAN ONE {suffix} object. For quantification, you must only have ONE {suffix} object, attempting to correct this automatically...")
#             filtered_obj_seg = QC_filter(edited, raw, method=filt)

#             if len(np.unique(filtered_obj_seg)) == 2:
#                 print(f"The image has been processed to automatically remove any small objects using the {filt} method.")
#                 viewer2.add_image(raw, name=f'{suffix}_raw', blending='additive')
#                 viewer2.add_labels(edited, name=f'{suffix}_seg')
#                 viewer2.add_labels(filtered_obj_seg, name=f'{suffix}_seg_filtered')
#                 settings = get_settings()
#                 settings.application.ipy_interactive = False
#                 print(f"Head to the Napari window to see your filtered {suffix} segmentation output!")
#                 print(f"Note: if further edits are desired, please edit the {suffix}_seg layer instead of the {suffix}_seg_filtered layer.")
#                 print("Please close the Napari window to continue.")
                
#                 napari.run()
#                 settings.application.ipy_interactive = True

#                 if not (filtered_obj_seg == viewer2.layers[f'{suffix}_seg_filtered'].data).all():
#                     print(f"You have erroneously eddited the {suffix}_seg_filtered layer, restarting from beginning of the filtering process...")
#                     return filter_segmentation(suffix, filt, edited, raw, status)

#                 if (viewer2.layers[f'{suffix}_seg'].data == edited).all():
#                     print(f"You appear satsified with the {suffix} segmentation, saving...")     
#                     status = "Pass"
#                     return (filtered_obj_seg, status)
#                 else:
#                     print(f"You have edited the {suffix}_seg layer, now retrying the filtering process...")
#                     return filter_segmentation(suffix, filt, viewer2.layers[f'{suffix}_seg'].data, raw, status)
#             elif len(np.unique(filtered_obj_seg)) > 2:
#                 print("We tried to remove small objects, but there are still multiple cell mask objects in the image. Please try other 'filter_cell' values above or edit the segmentation manually in Napari again.")
#                 viewer2.add_image(raw, name=f'{suffix}_raw', blending='additive')
#                 viewer2.add_labels(edited, name=f'{suffix}_seg')
#                 viewer2.add_labels(filtered_obj_seg, name=f'{suffix}_seg_filtered')
#                 settings = get_settings()
#                 settings.application.ipy_interactive = False
#                 print(f"Head to the Napari window to see your filtered {suffix} segmentation output!")
#                 print(f"Note: please edit the {suffix}_seg layer instead of the {suffix}_seg_filtered layer, or change the filter type chosen for this segmentation and rerun the block when prompted later.")
#                 print("Please close the Napari window to continue.")
#                 napari.run()
#                 settings.application.ipy_interactive = True
#                 if not (filtered_obj_seg == viewer2.layers[f'{suffix}_seg_filtered'].data).all():
#                     print(f"You have erroneously eddited the {suffix}_seg_filtered layer, restarting from beginning of the filtering process...")
#                     return filter_segmentation(suffix, filt, edited, raw, status)

#                 if not (viewer2.layers[f'{suffix}_seg'].data == edited).all():
#                     print(f"You have edited the {suffix}_seg layer, now retrying the filtering process...")
#                     return filter_segmentation(suffix, filt, viewer2.layers[f'{suffix}_seg'].data, viewer2.layers[f'raw'].data, status)
#                 else:
#                     print(f"As you have not chosen to edit the {suffix}_seg layer, we will now return the previous segmentation.")
#                     return (edited, status)
#             else:
#                 print("There are no objects in the segmentation... Please check your segmentation files, and/or obj_filter value. We will now return the prior segmentation.")
#                 return (edited, status)
#         else:
#             print(f"Your {suffix} segmentation looks good, no corrections needed!")
#             status = "Pass"
#             return (edited, status)
#     else:
#         print(f"You have chosen not to filter the {suffix} segmentation, returning original segmentation...")
#         return (edited, status)

In [ ]:
from infer_subc.utils.batch import filter_segmentation
if len(quality_filter) != len(obj_segs.keys()):
    print("The number of values in the quality filter is not equal to the number of object segmentations.")
    print("Please adjust the values in the quality_filter variable above, then rerun this block of code.")
else:
    if all(map(lambda v: v is None, obj_segs_edit.values())):
        obj_segs_edit = obj_segs
    filtered_obj_segs_edit = {key: None for key in obj_segs_edit.keys()}
    status_table = pd.DataFrame(columns=['Status'], index=obj_segs_edit.keys())
    for suffix, filt in zip(obj_segs_edit.keys(), quality_filter):
        if status_table.at[suffix, 'Status'] is None:
            status_table.at[suffix, 'Status'] = 'N/A'
        if (filtered_obj_segs_edit[suffix] is None) or (filt is not None):
            try:
                filter_out = filter_segmentation(suffix, filt, obj_segs_edit[suffix], raw_img_data, status_table.at[suffix, 'Status'])
                filtered_obj_segs_edit[suffix] = filter_out[0]
                status_table.at[suffix, 'Status'] = filter_out[1]
            except (ValueError, KeyError):
                print(f"No raw image found for {suffix}, adding the 'raw' layer instead.")
                filter_out = filter_segmentation(suffix, filt, obj_segs_edit[suffix], viewer.layers['raw'].data, status_table.at[suffix, 'Status'])
                filtered_obj_segs_edit[suffix] = filter_out[0]
                status_table.at[suffix, 'Status'] = filter_out[1]

    print("Below is the status of the segmentations after the quality control checks:")
    display(status_table)
    if (status_table['Status'] == 'Fail').any():
        print("You have not passed the quality control checks for all segmentations, please make changes to the segmentations that have failed the QC checks.")
        print("These changes may be reediting the image, or rerunning the filter_segmentation function with different filter values.")
        print("Once you have made these changes, please rerun this block of code to revalidate the segmentation status.")
    else:
        print("You have passed the quality control checks for all segmentations.")
        print("Please proceed to the next step.")

You have chosen not to filter the nuc segmentation, returning original segmentation...

WARNING: QWindowsWindow::setGeometry: Unable to set geometry 1280x1140+12+46 (frame: 1302x1196+1+1) on QWidgetWindow/"_QtMainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 1280x1050+12+46 (frame: 1302x1106+1+1) margins: 11, 45, 11, 11 minimum size: 385x491 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=792,1038 maxtrack=0,0)
27-Aug-25 13:01:27 - vispy    - WARNING  - QWindowsWindow::setGeometry: Unable to set geometry 1280x1140+12+46 (frame: 1302x1196+1+1) on QWidgetWindow/"_QtMainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 1280x1050+12+46 (frame: 1302x1106+1+1) margins: 11, 45, 11, 11 minimum size: 385x491 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=792,1038 maxtrack=0,0)

Your cell segmentation contains MORE THAN ONE cell object. For quantification, you must only have ONE cell object, attempting to correct this automatically...
Applying size filter with linear size...
The image has been processed to automatically remove any small objects using the 100 method.
Head to the Napari window to see your filtered cell segmentation output!
Note: if further edits are desired, please edit the cell_seg layer instead of the cell_seg_filtered layer.
Please close the Napari window to continue.
You appear satsified with the cell segmentation, saving...
You have chosen not to filter the lyso2 workflow segmentation, returning original segmentation...
You have chosen not to filter the mito segmentation, returning original segmentation...
You have chosen not to filter the APOE371_BR1_N07 segmentation, returning original segmentation...
You have chosen not to filter the peroxisome workflow segmentation, returning original segmentation...
You have chosen not to filter the ER segmentation, returning original segmentation...
You have chosen not to filter the Lipid Droplet Workflow segmentation, returning original segmentation...
Below is the status of the segmentations after the quality control checks:

                       Status
nuc                       NaN
cell                     Pass
lyso2 workflow            NaN
mito                      NaN
APOE371_BR1_N07           NaN
peroxisome workflow       NaN
ER                        NaN
Lipid Droplet Workflow    NaN

You have passed the quality control checks for all segmentations.
Please proceed to the next step.

WARNING: QWindowsWindow::setGeometry: Unable to set geometry 1920x1140+0+34 (frame: 1942x1196-11-11) on QWidgetWindow/"_QtMainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 1920x986+0+34 (frame: 1942x1042-11-11) margins: 11, 45, 11, 11 minimum size: 510x570 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=1042,1196 maxtrack=0,0)
27-Aug-25 13:01:29 - vispy    - WARNING  - QWindowsWindow::setGeometry: Unable to set geometry 1920x1140+0+34 (frame: 1942x1196-11-11) on QWidgetWindow/"_QtMainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 1920x986+0+34 (frame: 1942x1042-11-11) margins: 11, 45, 11, 11 minimum size: 510x570 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=1042,1196 maxtrack=0,0)

> #### &#x1F6D1; **STOP: Review the output of the above block of code.** &#x1F50E;
> 
> **At this point, take note of which segmentations have failed the quality check, if any. Once you are finished reviewing the segmentations for this image, follow the steps the block of code has outlined for you:**
> 1) If you have any segmentations fail quality checks, review the segmentation and potentially re-edit it.
> 2) If none of your segmentations fail quality checks, proceed to the next step.

### **`STEP 5` - Save segmentations**

#### &#x1F3C3; **Run code; no user input required**

Now that your segmentations have passed quality control, you can save them using the below block of code.

In [17]:
if (status_table['Status'] == 'Fail').any():
    print("You have not passed the quality control checks for your segmentations. Please return to earlier steps, and adjust your segmentations to meet the assumptions made by the program.")
else:
    for suffix in filtered_obj_segs_edit.keys():
        export_inferred_organelle(filtered_obj_segs_edit[suffix], suffix, raw_meta_dict, Path(location_tosave_fullset_gooddata), seg_file_type)

TypeError: export_inferred_organelle() takes 4 positional arguments but 5 were given

> ### 🔁🔁 **Repeat `Steps 2-5` above for *EACH IMAGE* in your dataset.**  
>
> You've now completed the quality check for one image. Repeat these steps for each image in your dataset by selecting the next image in the list at the beginning of `Step 2` above.

-----
### 🎉 **CONGRATULATIONS!! You've successfully completed `infer-subc Part 1 - Segmentation Workflows`.**

Continue on to `infer-subc Part 2 - Organelle Quantification`. An overview is included in the [`2.0_quantification_setup`](..\part_2_quantification\2.0_quantification_setup.ipynb) notebook.