# **Measure Organelle Interactions**

<mark> **SOMETHINGS WRONG IN THE CODE BELOW** - maybe related to input confusion** </mark>

***Prior to this notebook, you should have already run through [2.0_quantification_setup](2.0_quantification_setup.ipynb).***

The `'methods_...'` notebooks included here in infer-subc Part 2: quantification will go over how each of the quantification methods (morphology, interactions, and distribution) are carried out. The notebooks will explain each step in the method and display the combined function at the end of the notebook. 

### **Biological Relevance**
Intracellular organelles do not exist independently of one another. In recent years, the existance and function of organelle contact site, regions of close apposition between membrane bound organelles has been recognized. They facilitate protein, lipid, and metabolite transport, coordinate organelle trafficking and function, and are involved in many cellular pathways and functions [[1](https://www.cell.com/cell/pdf/S0092-8674(23)01328-4.pdf)]. 

The distance between membranes at contact sites is between 30-80 nm depending on the types of organelles involved. This distance is not resolvable using standard confocal microscopy images [[2](https://zeiss-campus.magnet.fsu.edu/articles/basics/resolution.html)]. However, "interactions" between organelle which can include organelle contact sites or other physiological interactions such as cotrafficking of organelles using the same machinery, can be estimated through colocalization (overlap) of segmented objects in confocal microscopy images.

The amount, size, shape, and distribution of interaction sites can be informative of complex metabolic and functional states beyond what the study of a single organelle could reveal.

### **Oragnelle Interactions** 📐
Here, we will use the overlapping area between two or more segmented organelle objects as putative interaction sites.

- `Organelle interaction sites`: regions of overlap between two or more organelles

The notebook will walk through how these interaction sites are created for different combinations of organelles. These sites will then be measured for features such as number, size, and shape utilizing the `get_morpholgy_metrics()` function outlined in [method_morphology](method_morphology.ipynb) notebook and/or measurements of subcellular distribution utilizing the `get_distribution()` function outlined in [method_distribution](method_distribution.ipynb) notebook.

# **NOTES**

<mark> **1. MAKE IT OPTIONAL TO APPLY MORPH AND DIST FUNCTIONS** </MARK>

-----

### 👣 **Summary of steps**  

🛠️ **BUILD FUNCTION STEP-BY-STEP**

- **`STEP 1`** - Select organelles of interest (make_dict)

- **`STEP 2`** - Create interaction sites (create_overlap)

- **`STEP 3`** - Find the ID number of the organelles involved in each interaction site

⚙️ **DEFINE AND TEST `*Interactions*` FUNCTION**

- Define `get_interactions_metrics` function
- Run `get_interactions_metrics` function

The above steps will be applied to create a single interaction site of interest. Batch processing and quantification are available in the [2.2_organelle_interactions](./2.2_organelle_interactions.ipynb) notebook.

---------------------
## **IMPORTS AND LOAD IMAGE**
Details about the functions included in this subsection are outlined in the [`2.0_quantification_setup`](2.0_quantification_setup.ipynb) notebook. Please visit that notebook first if you are confused about any of the code included here.

In [55]:
from pathlib import Path
import os
import warnings

import pandas as pd
import numpy as np
import napari
import seaborn as sns
from napari.utils.notebook_display import nbscreenshot

from skimage.measure import (regionprops, regionprops_table)

from infer_subc.core.file_io import (read_czi_image,
                                     import_inferred_organelle,
                                     list_image_files)

from infer_subc.core.img import *
from infer_subc.quantification.stats import *
from infer_subc.quantification.stats import (_assert_uint16_labels)
from infer_subc.quantification.stats_helpers import *
from infer_subc.organelles import * 

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

#### &#x1F3C3; **Run code; no user input required**

#### &#x1F6D1; &#x270D; **User Input Required:**

Please specify the following information about your data: `raw_img_type`, `data_root_path`, `raw_data_path`, `seg_data_path`, and `quant_data_path`.

In [56]:
#### USER INPUT REQUIRED ###
raw_img_type = ".czi"
data_root_path = Path(os.path.expanduser("~")) / "Documents/Python_Scripts/Infer-subc"
raw_data_path = data_root_path / "raw_single"
seg_data_path = data_root_path / "out_single"
quant_data_path = data_root_path / "quant_single"

#### &#x1F3C3; **Run code; no user input required**

In [57]:
# Create the output directory to save the segmentation outputs in.
if not Path.exists(quant_data_path):
    Path.mkdir(quant_data_path)
    print(f"making {quant_data_path}")

# Create a list of the file paths for each image in the input folder. Select test image path.
raw_img_file_list = list_image_files(raw_data_path,raw_img_type)
pd.set_option('display.max_colwidth', None)
pd.DataFrame({"Image Name":raw_img_file_list})

                                                                                    Image Name
0  C:\Users\Shannon\Documents\Python_Scripts\Infer-subc\raw_single\a24hrs_Ctrl_14_Unmixing.czi

#### &#x1F6D1; &#x270D; **User Input Required:**

Use the list above to specify which image you wish to analyze based on its index: `test_img_n`

In [58]:
#### USER INPUT REQUIRED ###
test_img_n = 0

#### &#x1F3C3; **Run code; no user input required**

In [59]:
# Read in the image and metadata as an ndarray and dictionary from the test image selected above. 
test_img_name = raw_img_file_list[test_img_n]
img_data,meta_dict = read_czi_image(test_img_name)

# Define some of the metadata features.
channel_names = meta_dict['name']
meta = meta_dict['metadata']['aicsimage']
scale = meta_dict['scale']
channel_axis = meta_dict['channel_axis']
file_path = meta_dict['file_name']

print("Metadata information")
print(f"File path: {file_path}")
for i in list(range(len(channel_names))):
    print(f"Channel {i} name: {channel_names[i]}")
print(f"Scale (ZYX): {scale}")
print(f"Channel axis: {channel_axis}")

Metadata information
File path: C:\Users\Shannon\Documents\Python_Scripts\Infer-subc\raw_single\a24hrs_Ctrl_14_Unmixing.czi
Channel 0 name: 0 :: a24hrs_Ctrl_14_Unmixing-0 :: Nuclei_Jan22
Channel 1 name: 0 :: a24hrs_Ctrl_14_Unmixing-0 :: Lyso+405_Jan22
Channel 2 name: 0 :: a24hrs_Ctrl_14_Unmixing-0 :: Mito+405_Jan22
Channel 3 name: 0 :: a24hrs_Ctrl_14_Unmixing-0 :: Golgi+405_Jan22
Channel 4 name: 0 :: a24hrs_Ctrl_14_Unmixing-0 :: Peroxy+405_Jan22
Channel 5 name: 0 :: a24hrs_Ctrl_14_Unmixing-0 :: ER+405_Jan22
Channel 6 name: 0 :: a24hrs_Ctrl_14_Unmixing-0 :: BODIPY+405low_Jan22
Channel 7 name: 0 :: a24hrs_Ctrl_14_Unmixing-0 :: Residuals
Scale (ZYX): (0.3891184878080979, 0.07987165184837317, 0.07987165184837318)
Channel axis: 0

#### &#x1F6D1; &#x270D; **User Input Required:**

Specify the following information about the segmentation files: - `org_file_names`, `org_channels_ordered`, `regions_file_names`, `suffix_separator`, and `mask_name`.

In [60]:
#### USER INPUT REQUIRED ###
org_file_names = ["lyso", "mito", "golgi", "perox", "ER", "LD"]
org_channels_ordered = [1, 2, 3, 4, 5, 6]
regions_file_names = ["cell", "nuc"]
suffix_separator = "-"
mask_name = "cell"

#### &#x1F3C3; **Run code; no user input required**

In [61]:
# find file paths for segmentations
all_suffixes = org_file_names + regions_file_names
filez = find_segmentation_tiff_files(file_path, all_suffixes, seg_data_path, suffix_separator)

# read the segmentation and masks/regions files into memory
organelles = [read_tiff_image(filez[org]) for org in org_file_names]
regions = [] 
for m in regions_file_names:
    mfile = read_tiff_image(filez[m])
    regions.append(mfile)

# match the intensity channels to the segmentation files
intensities = [img_data[ch] for ch in org_channels_ordered]

# specifiy the mask image
m = regions_file_names.index(mask_name)
mask = regions[m]

# open viewer and add images
viewer = napari.Viewer()
for r, reg in enumerate(regions_file_names):
    viewer.add_image(regions[r],
                     scale=scale,
                     name=f"{reg} mask")

for o, org in enumerate(org_file_names):
    viewer.add_image(intensities[o],
                     scale=scale,
                     name=f"{org} intensity channel")
    viewer.add_labels(organelles[o],
                      scale=scale,
                      name=f"{org} segmentation")
viewer.grid.enabled = True
viewer.reset_view()

print("The following matching files were found and can now be viewed in Napari:")
filez

The following matching files were found and can now be viewed in Napari:

{'raw': WindowsPath('C:/Users/Shannon/Documents/Python_Scripts/Infer-subc/raw_single/a24hrs_Ctrl_14_Unmixing.czi'),
 'lyso': WindowsPath('C:/Users/Shannon/Documents/Python_Scripts/Infer-subc/out_single/a24hrs_Ctrl_14_Unmixing-lyso.tiff'),
 'mito': WindowsPath('C:/Users/Shannon/Documents/Python_Scripts/Infer-subc/out_single/a24hrs_Ctrl_14_Unmixing-mito.tiff'),
 'golgi': WindowsPath('C:/Users/Shannon/Documents/Python_Scripts/Infer-subc/out_single/a24hrs_Ctrl_14_Unmixing-golgi.tiff'),
 'perox': WindowsPath('C:/Users/Shannon/Documents/Python_Scripts/Infer-subc/out_single/a24hrs_Ctrl_14_Unmixing-perox.tiff'),
 'ER': WindowsPath('C:/Users/Shannon/Documents/Python_Scripts/Infer-subc/out_single/a24hrs_Ctrl_14_Unmixing-ER.tiff'),
 'LD': WindowsPath('C:/Users/Shannon/Documents/Python_Scripts/Infer-subc/out_single/a24hrs_Ctrl_14_Unmixing-LD.tiff'),
 'cell': WindowsPath('C:/Users/Shannon/Documents/Python_Scripts/Infer-subc/out_single/a24hrs_Ctrl_14_Unmixing-cell.tiff'),
 'nuc': WindowsPath('C:/Users/Shannon/Documents/Python_Scripts/Infer-subc/out_single/a24hrs_Ctrl_14_Unmixing-nuc.tiff')}

-----
## **QUANTIFY INTERACTIONS BETWEEN *two or more organelles* FROM <INS>ONE CELL</INS>**

### **`STEP 1` - Select organelles of interest**

#### &#x1F6D1; &#x270D; **User Input Required:**

Please specify which organelles you would like to examine in this analysis:
- `org_name_list`: a list of the organelle names you would like to measure interactions for; each name should exactly match one of the file suffixes included in the "org_file_names" variable above.

In [62]:
#### USER INPUT REQUIRED ###
org_to_include = ["lyso", "mito", "perox"]

#### &#x1F3C3; **Run code; no user input required**

&#x1F453; **FYI:** This block of code used the organelle names specified in the `org_name_list` variable above to create a dictionary of images. The organelle names will be the keys and the associated segmentation images are included as the values. The name of the interaction site is also created and printer below.


> **Example outputs**
>
> Image dictionary:
> ```
> {"lyso": np.ndarray,
>  "mito": np.ndarray,
>  "perox": np.ndarray}
>  ```
>
> Interaction site name:
> ```
> "lyxoXmitoXperox"
> ```

In [63]:
# ensure at least two organelles are selected to define an interaction site
if len(org_to_include)<2:
    raise ValueError("Please select at least two organelles to define an interaction site.")
else:

    # select the associated organelle segmentations
    org_segs = [organelles[org_file_names.index(org)] for org in org_to_include]

    # create name for interaction site
    interaction_name = "X".join(org_to_include)
    print("The name of the interaction site is:", interaction_name)

    # create function to easily make dictionary of organelle segmentations
    def _make_dict(list_obj_names: list[str],
                list_obj_segs: list[np.ndarray]) -> dict[str:np.ndarray]:
        '''
        Create a dictionary of organelle segmentations from a list of organelle names and a list of organelle segmentation arrays.

        Parameters
        ----------
        list_obj_names : list[str]
            A list of organelle names as strings.
        list_obj_segs : list[np.ndarray]
            A list of organelle segmentation image arrays as numpy ndarrays.

        Returns
        -------
        organelle_segs : dict[str:np.ndarray]
            A dictionary of organelle segmentations with organelle names as keys and segmentation arrays as values
        '''

        organelle_segs = {}                                                     
        for idx, name in enumerate(list_obj_names):                                  
            if name == 'ER':                                                    
                organelle_segs[name]=(list_obj_segs[idx]>0).astype(np.uint16)        
            else:                                                       
                organelle_segs[name]=list_obj_segs[idx]
                
        return organelle_segs


    # run function to create dictionary of organelle segmentations
    org_dict = _make_dict(org_to_include, org_segs)
    print("The organelles segmentations included are:", list(org_dict.keys()))

The name of the interaction site is: lysoXmitoXperox
The organelles segmentations included are: ['lyso', 'mito', 'perox']

### **`STEP 2` - Create interaction sites**

#### &#x1F3C3; **Run code; no user input required**

&#x1F453; **FYI:** This block of code selects the pixels/voxels within the image that are shared between the selected organelles. The output is included in the Napari window.

<mark> decide where to put the seaborn color pallet selection - seems like 2.0 and in the read image would be a better location

In [64]:
# function to create an image of the overlap regions between the selected organelles
def _create_overlap(orgs:str,
                    organelle_segs: dict[str:np.ndarray],
                    splitter: str="X") -> tuple[np.ndarray, np.ndarray]:
    '''
    Create an image of the overlap regions between the selected organelles.

    Parameters
    ----------
    orgs : str
        A string of organelle names separated by the specified splitter.
    organelle_segs : dict[str:np.ndarray]
        A dictionary of organelle segmentations with organelle names as keys and segmentation image arrays as values.
    splitter : str, optional
        The character used to split the organelle names in the orgs string, by default "X". 
        For example, "mitoXlyso" would indicate an interaction between mito and lyso.
    
    Returns
    -------
    site : np.ndarray
        An image array of the overlap regions between the selected organelles, with unique integer IDs for each interaction site.
    '''
    site = np.ones_like(organelle_segs[orgs.split(splitter)[0]]) 
    for org in orgs.split(splitter):        
        b = organelle_segs[org]             # select organelle
        valid = (b>0)*(site>0)              # logical and: select MASK of region where site (everything or previous overlap) overlaps with org b
        digit = len(str(np.max(site)))      # find the max ID number in the site image
        site = (b*(10**(digit)))+site       # multiply the organelle b image by 10^digit (up to the next highest multiplier of 10 compared to the original org number per image) then add the site image to that --> preservation of declumped objects
        site[valid.astype(bool)==False]=0   # select everywhere outside the overlap in the site image and get rid of it --> only object multiplied by 10^digit, but now there is separation between declumped neighbors inherited from the original ID numbers added in
        site = label(site)                  # label the overlap to minimize the max number & provide logical number system to contacts in end
    return site

# create the overlap image
overlap_img = _create_overlap(interaction_name, org_dict)

# visualize in the napari viewer with distinct colors for each organelle
n_org = len(organelles)
if n_org<=10:
    colors = sns.color_palette(palette="colorblind", n_colors=len(organelles)).as_hex()
elif n_org>10 and n_org<=20:
    colors = sns.color_palette(palette="tab20", n_colors=len(organelles)).as_hex()
else:
    colors = sns.color_palette(palette="hsv", n_colors=len(organelles)).as_hex()
    Warnings.warn("More than 20 organelles selected. Colors may be hard to distinguish.")

for i, stuff in enumerate(org_dict.items()):
    viewer.add_image(stuff[1]>0, scale=scale, name=f"{stuff[0]} segmentation", blending='additive', colormap=colors[i])
viewer.add_image(overlap_img>0, scale=scale, name=f"{interaction_name} overlap", opacity=0.6)

### **`STEP 3` - List the ID numbers of the organelles involved in each interaction site**

#### &#x1F3C3; **Run code; no user input required**

&#x1F453; **FYI:** This block of code identifies the organelle ID numbers associated to each interaction site and creates an interaction site label based upon them. The interaction site lables are formatted as is shown in this example:

> **Components within an interaction site:**
> | *Organelles*    | *Organelle IDs*   |
> | :-------------- |  :--------------: | 
> | mito            |   1               |
> | lyso            |   27              | 
>
> **Interaction site name:** "mitoXlyso"
>
> **Interaction site label:** 1_27


The list of interaction site indexes and associated organelle IDs are included in the output table.

In [65]:
# use regionprops table to list interaction sites by unique index and extract slice for each object
props = regionprops_table(overlap_img, properties=['label', 'slice'])

# create a list of the organelle ID numbers involved in each interaction site
over_inv = []
involved = interaction_name.split("X")
indexes = {interaction_name: []}

for index, l in enumerate(props["label"]):
    over_inv.clear()
    for org in involved:
        volume = overlap_img[props["slice"][index]]
        lorg = org_dict[org][props["slice"][index]]
        volume = volume==l
        lorg = lorg[volume]                                 
        all_inv = np.unique(lorg[lorg>0]).tolist()          
        if len(all_inv) != 1:
            print(f"we have an error.  as-> {all_inv}") # ensure that only one org object is 
        over_inv.append(f"{all_inv[0]}")
    indexes[interaction_name].append('_'.join(over_inv))

# add the organelle ID list to the table
inter_tab = pd.DataFrame(props)
inter_tab.insert(1, 'object', interaction_name, True)
inter_tab.rename(columns={'label': 'idx'}, inplace=True)
inter_tab.insert(2, 'label',value=indexes[interaction_name])
inter_tab.drop(columns=['slice'], inplace=True)

inter_tab

Empty DataFrame
Columns: [idx, object, label]
Index: []

### **`DEFINE` - `get_interaction_metrics` function**

The following code combines the steps above into a single function. The function creates a single interaction site image array that displays the regions of overlap between all specified organelles and a table of unique identifiers associated to each interaction site. This function is utilized in the [2.2_organelle_interactions](./2.2_organelle_interactions.ipynb) notebook where interaction analysis can be applied to many different interaction site types across one or more cells.

This function can be utilized from infer-subc using:
```python
infer_subc.utils.stats.get_morphology_metrics()
```
<mark>update this location to match eventually!!!</mark>

#### &#x1F3C3; **Run code; no user input required**

&#x1F453; **FYI:** This code block defines the `get_unique_interaction_sites()` function. It is applied below.

In [ ]:
def _get_unique_interaction_sites(orgs:List[str],
                                  segs: List[np.ndarray],
                                  splitter: str="X") -> tuple[np.ndarray, pd.DataFrame]:
    
    '''
    Create an image of the overlap regions between the selected organelles and a table of unique identifiers associated to each interaction site.
    Parameters 
    ----------
    orgs : List[str]
        A list of organelle names as strings. These will be the organelles included in the interaction site output image.
    segs : List[np.ndarray]
        A list of organelle segmentation images as numpy ndarrays. These should be in the same order as the orgs list.
    splitter : str, optional
        The character used to split the organelle names in the orgs string, by default "X". 
        For example, "mitoXlyso" would indicate an interaction between mito and lyso.
    Returns
    -------
    overlap_img : np.ndarray
        An image array of the overlap regions between the selected organelles, with unique integer IDs for each interaction site.   
    inter_tab : pd.DataFrame
        A pandas DataFrame table with unique identifiers associated to each interaction site.
        `idx`: unique integer ID for each interaction site in the overlap image.
        `object`: the name of the interaction site, created by joining the organelle names with the specified splitter.
        `label`: a string of organelle ID numbers involved in each interaction site, joined by underscores.
    '''
    if len(orgs)<2:
        raise ValueError("Please select at least two organelles to define an interaction site.")
    else:
        # create name for interaction site
        interaction_name = splitter.join(orgs)

        # run function to create dictionary of organelle segmentations
        org_dict = _make_dict(orgs, segs)

        # create the overlap image
        overlap_img = _create_overlap(interaction_name, org_dict)

        # use regionprops table to list interaction sites by unique index and extract slice for each object
        props = regionprops_table(overlap_img, properties=['label', 'slice'])

        over_inv = []
        involved = interaction_name.split(splitter)
        indexes = {interaction_name: []}

        for index, l in enumerate(props["label"]):
            over_inv.clear()
            for org in involved:
                volume = overlap_img[props["slice"][index]]
                lorg = org_dict[org][props["slice"][index]]
                volume = volume==l
                lorg = lorg[volume]                                 
                all_inv = np.unique(lorg[lorg>0]).tolist()          
                if len(all_inv) != 1:
                    print(f"we have an error.  as-> {all_inv}") # ensure that only one org object is 
                over_inv.append(f"{all_inv[0]}")
            indexes[interaction_name].append('_'.join(over_inv))

        # add the organelle ID list to the table
        inter_tab = pd.DataFrame(props)
        inter_tab.insert(1, 'object', interaction_name, True)
        inter_tab.rename(columns={'label': 'idx'}, inplace=True)
        inter_tab.insert(2, 'label',value=indexes[interaction_name])
        inter_tab.drop(columns=['slice'], inplace=True)

        return overlap_img, inter_tab

#### &#x1F3C3; **Run code; no user input required**

&#x1F453; **FYI:** This code block applies the function above to your test image. The settings specified above are applied here.

In [ ]:
# run the function above and compare it to the precious results
out_image, out_tab = _get_unique_interaction_sites(org_to_include, org_segs)

print("The image output here matches the output created above:")
if np.array_equal(out_image,overlap_img):
    print('\033[92mTrue\033[0m')
else:
    print('\033[91mFalse\033[0m')

print("The table output here matches the output created above:")
if inter_tab.equals(out_tab):
    print('\033[92mTrue\033[0m')
else:
    print('\033[91mFalse\033[0m')